version: "3"

services: 
  app:
    build: .
    command : npm start
    
    ports: 
      - "3000:3000"
  db:
    image: mongo
    container_name: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
